apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    dynatrace.com/serverless: pod-scaler
    app: app-x
  name: dynatrace-pod-scaler
  namespace: app-x
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/ephemeralcontainers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-pods
  namespace: app-x
  labels:
    app: app-x
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: dynatrace-pod-scaler
  apiGroup: rbac.authorization.k8s.io